import repeatfinder

seq = 'agaattaaaactaattactgctcatattggaaatggtgtctcaattacagctaattaccacggtaaatcagttgatacctcgatgggctttacaccacttgctggtcctatgatgggaacacgttctggtgacattgacccagctatcattccttatttaattgagcaagacccagagttaaaagacgctgctgacgttgttaatatgttaaacaaaaaatcaggtcttagtggggtgtcaggcatttctagtgatatgcgtgatatcgaggctggtttacaagaagataatccagatgctgttttagcttacaatatctttattgatcgcattaaaaaatgcattggtcaatattttgctgttttgaatggagcagatgctttggtctttacagctggtatgggtgaaaatgcaccattgatgcgtcaagatgttattggtggcttaacatggttcggaatggacattgatcctgagaaaaatgtttttggataccgtggtgacatttcaactcctgagtcaaaagtgaaggtgcttgttatctcaacagacgaagaattgtgcatcgcgcgtgacgttgaacgtttaaaaaatacaaaataaaagagactaagtctcaatagattaaccaagtatgctcatattggaaatggtgtctcaattacaaggtaacactttacttggtttt'

status = repeatfinder.get_repeats(seq)

print(status)
